import { notFound } from "next/navigation";
import { Shell } from "@/components/Shell";
import { Inspector, InspectorRow } from "@/components/Inspector";
import { claims, isProduct, latestAudit } from "@/lib/data";
import * as auditModel from "@core/audit";
import type { DiffItem } from "@/types/core";

export const dynamic = "force-dynamic";

const SITE: Record<string, string> = {
  deckle: "getdeckle.dev",
  marskel: "marskel.com",
  echoself: "myechoself.com"
};

function Meter({ value, max }: { value: number; max: number }) {
  return (
    <span className="meter" aria-label={`${value} out of ${max}`}>
      {Array.from({ length: max }, (_, i) => (
        <i key={i} className={i < value ? "on" : ""} />
      ))}
    </span>
  );
}

function DiffBlock({ item }: { item: DiffItem }) {
  return (
    <article className={`diff ${item.held ? "is-held" : ""}`}>
      <div className="diffhead">
        <span className="label">{item.impact} impact</span>
        <span className="mono" style={{ fontSize: 12, color: "var(--ink-faint)" }}>{item.question}</span>
        {item.held ? <span className="badge blocked"><i />held</span> : null}
      </div>
      <div className="diffbody">
        <div className="row out"><span className="sign">-</span><span>{item.current}</span></div>
        <div className="row in"><span className="sign">+</span><span>{item.replacement}</span></div>
      </div>
      {item.why ? <p className="plain" style={{ marginTop: 10 }}>{item.why}</p> : null}
      {item.held ? <p className="chnote" style={{ marginTop: 10 }}>{item.heldReason}. This one cannot ship until the benchmark exists.</p> : null}
    </article>
  );
}

export default async function Audit({ params }: { params: Promise<{ product: string }> }) {
  const { product } = await params;
  if (!isProduct(product)) notFound();

  const [raw, proof] = await Promise.all([latestAudit(product), claims(product, "proof")]);
  const built = auditModel.build(raw, proof);

  const inspector = (
    <Inspector>
      <InspectorRow k="Scored before the diff" v="so a weak page cannot be fixed cosmetically" />
      <InspectorRow k="Held" v="a replacement that cites proof the product does not have. shown, not hidden" />
      <InspectorRow k="Never merges" v="the app opens a pull request. a human merges it, for the same reason it never posts" />
      <InspectorRow k="Generated by" v="the landing-audit skill, into products/<slug>/audits/" mono />
    </Inspector>
  );

  if (!built.exists) {
    return (
      <Shell slug={product} page="audit" title="Audit" when={SITE[product]} inspector={inspector}>
        <div className="empty">
          <h2>No audit in the last fortnight.</h2>
          <p>Run the landing-audit skill against {SITE[product]}. It writes into products/{product}/audits/ and this page reads it.</p>
        </div>
      </Shell>
    );
  }

  return (
    <Shell slug={product} page="audit" title="Audit" when={`${built.url ?? SITE[product]} . ${built.date}`} inspector={inspector}>
      <div className="scorehead">
        <div>
          <span className="label">Score</span>
          <div className="mono scoretotal">{built.score.total} <span>/ {built.score.max}</span></div>
          <div className="mono" style={{ fontSize: 12, color: "var(--ink-faint)" }}>{built.score.verdict}</div>
        </div>
        <div className="rubric">
          {built.score.rows.map((row) => (
            <div className={`rubricrow ${row.weak ? "weak" : ""}`} key={row.key}>
              <span className="mono n">{row.n}</span>
              <span className="q">{row.question}</span>
              <Meter value={row.value} max={5} />
              <span className="mono v">{row.value}</span>
            </div>
          ))}
        </div>
      </div>

      <p className="plain">
        The score comes before the diff on purpose. A page scoring {built.score.total} out of {built.score.max} is
        not fixed by better words in the same places.
      </p>

      <div className="hairline" />

      <div>
        <div className="sechead" style={{ marginBottom: 12 }}>
          <span className="label">Prioritized diff</span>
          <span className="mono" style={{ fontSize: 12, color: "var(--ink-faint)", marginLeft: "auto" }}>
            {built.shippable.length} shippable, {built.held.length} held
          </span>
        </div>
        {built.items.map((item, i) => <DiffBlock key={item.id ?? i} item={item} />)}
      </div>

      {built.pullRequest ? (
        <div className="prbox">
          <span className="label">Pull request</span>
          <div className="mono" style={{ fontSize: 13, margin: "8px 0 4px" }}>{built.pullRequest.branch}</div>
          <p className="plain" style={{ margin: "0 0 12px" }}>
            {built.pullRequest.files} change{built.pullRequest.files === 1 ? "" : "s"} ready.
            {built.held.length ? ` ${built.held.length} held, waiting on proof.` : ""}
          </p>
          <a className="btn primary" href={`https://github.com/Yoshyaes/${product}`} target="_blank" rel="noreferrer">
            Review on GitHub
          </a>
          <p className="plain" style={{ marginTop: 12, color: "var(--ink-faint)" }}>
            Opened, not merged. Audit and fix in one session is the step a subscription tool cannot take.
          </p>
        </div>
      ) : null}
    </Shell>
  );
}
