"use strict";
const { esc } = require("../../lib/html");
const repo = require("../../lib/repo");
const auditModel = require("../../lib/audit");
const fs = require("fs");
const path = require("path");
const { page, inspectorRow } = require("../render");

const SITE = { deckle: "getdeckle.dev", marskel: "marskel.com", echoself: "myechoself.com" };

function latest(slug) {
  for (let i = 0; i < 14; i++) {
    const p = path.join(repo.PRODUCTS, slug, "audits", repo.daysAgo(i) + ".json");
    if (fs.existsSync(p)) {
      try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; }
    }
  }
  return null;
}

function meter(v, max) {
  let out = "";
  for (let i = 0; i < max; i++) out += '<i class="' + (i < v ? "on" : "") + '"></i>';
  return '<span class="meter">' + out + "</span>";
}

function diffBlock(item) {
  return [
    '<article class="diff ' + (item.held ? "is-held" : "") + '">',
    '<div class="diffhead">',
    '<span class="label">' + esc(item.impact) + ' impact</span>',
    '<span class="mono" style="font-size:12px;color:var(--ink-faint)">' + esc(item.question) + '</span>',
    item.held ? '<span class="badge blocked"><i></i>held</span>' : "",
    '</div>',
    '<div class="diffbody">',
    '<div class="row out"><span class="sign">-</span><span>' + esc(item.current) + '</span></div>',
    '<div class="row in"><span class="sign">+</span><span>' + esc(item.replacement) + '</span></div>',
    '</div>',
    item.why ? '<p class="plain" style="margin-top:10px">' + esc(item.why) + '</p>' : "",
    item.held ? '<p class="chnote" style="margin-top:10px">' + esc(item.heldReason) + '. This one cannot ship until the benchmark exists.</p>' : "",
    '</article>'
  ].join("");
}

function render(slug) {
  const built = auditModel.build(latest(slug), repo.claims(slug, "proof"));
  const site = SITE[slug] || slug;

  const inspector = [
    inspectorRow("Scored before the diff", "so a weak page cannot be fixed cosmetically"),
    inspectorRow("Held", "a replacement that cites proof the product does not have. shown, not hidden"),
    inspectorRow("Never merges", "the app opens a pull request. a human merges it, for the same reason it never posts"),
    inspectorRow("Generated by", "the landing-audit skill, into products/<slug>/audits/", true)
  ].join("");

  if (!built.exists) {
    return page({
      slug, page: "audit", title: "Audit", when: site, inspector,
      body: '<div class="empty"><h2>No audit in the last fortnight.</h2>' +
        '<p>Run the landing-audit skill against ' + esc(site) +
        '. It writes into products/' + esc(slug) + '/audits/ and this page reads it.</p></div>'
    });
  }

  const body = [
    '<div class="scorehead"><div>',
    '<span class="label">Score</span>',
    '<div class="mono scoretotal">' + built.score.total + ' <span>/ ' + built.score.max + '</span></div>',
    '<div class="mono" style="font-size:12px;color:var(--ink-faint)">' + esc(built.score.verdict) + '</div>',
    '</div><div class="rubric">',
    built.score.rows.map((row) =>
      '<div class="rubricrow ' + (row.weak ? "weak" : "") + '">' +
      '<span class="mono n">' + row.n + '</span>' +
      '<span class="q">' + esc(row.question) + '</span>' +
      meter(row.value, 5) +
      '<span class="mono v">' + row.value + '</span></div>').join(""),
    '</div></div>',

    '<p class="plain">The score comes before the diff on purpose. A page scoring ' + built.score.total +
      ' out of ' + built.score.max + ' is not fixed by better words in the same places.</p>',

    '<div class="hairline"></div>',

    '<div><div class="sechead" style="margin-bottom:12px">',
    '<span class="label">Prioritized diff</span>',
    '<span class="mono" style="font-size:12px;color:var(--ink-faint);margin-left:auto">' +
      built.shippable.length + ' shippable, ' + built.held.length + ' held</span>',
    '</div>',
    built.items.map(diffBlock).join(""),
    '</div>',

    built.pullRequest ? [
      '<div class="prbox">',
      '<span class="label">Pull request</span>',
      '<div class="mono" style="font-size:13px;margin:8px 0 4px">' + esc(built.pullRequest.branch) + '</div>',
      '<p class="plain" style="margin:0 0 12px">' + built.pullRequest.files + ' changes ready.' +
        (built.held.length ? " " + built.held.length + " held, waiting on proof." : "") + '</p>',
      '<a class="btn primary" href="https://github.com/Yoshyaes/' + esc(slug) + '" target="_blank" rel="noreferrer">Review on GitHub</a>',
      '<p class="plain" style="margin-top:12px;color:var(--ink-faint)">Opened, not merged. Audit and fix in one session is the step a subscription tool cannot take.</p>',
      '</div>'
    ].join("") : ""
  ].join("\n");

  return page({ slug, page: "audit", title: "Audit", when: (built.url || site) + " . " + built.date, body, inspector });
}
module.exports = { render };
